# Generated by Django 6.0.2 on 2026-02-08 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='usercurrencyrate',
            unique_together={('user', 'from_currency', 'to_currency')},
        ),
    ]
