# Generated by Django 6.0.2 on 2026-02-08 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wallet_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('account', 'Account')], max_length=10)),
                ('card_type', models.CharField(blank=True, choices=[('humo', 'Humo'), ('uzcard', 'Uzcard'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
